In [1]:
#import library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
import os

In [7]:
os.chdir('C:\\Users\\kandanulus\\MyTestlab\\wine')

In [8]:
wine = pd.read_csv('wine.csv')

In [9]:
wine.describe()

Year      Price  WinterRain       AGST  HarvestRain        Age  \
count    25.000000  25.000000   25.000000  25.000000    25.000000  25.000000   
mean   1965.800000   7.067224  605.280000  16.509336   148.560000  17.200000   
std       7.691987   0.650341  132.277965   0.675397    74.419464   7.691987   
min    1952.000000   6.204900  376.000000  14.983300    38.000000   5.000000   
25%    1960.000000   6.518800  536.000000  16.200000    89.000000  11.000000   
50%    1966.000000   7.121100  600.000000  16.533300   130.000000  17.000000   
75%    1972.000000   7.495000  697.000000  17.066700   187.000000  23.000000   
max    1978.000000   8.493700  830.000000  17.650000   292.000000  31.000000   

          FrancePop  
count     25.000000  
mean   49694.436760  
std     3665.270243  
min    43183.569000  
25%    46583.995000  
50%    50254.966000  
75%    52894.183000  
max    54602.193000

# Perform EDA

In [10]:
wine.columns

Index(['Year', 'Price', 'WinterRain', 'AGST', 'HarvestRain', 'Age',
       'FrancePop'],
      dtype='object')

In [168]:
X = wine[['WinterRain','AGST','HarvestRain']]
y = wine[['Price']]

In [169]:
from sklearn.model_selection import train_test_split

In [170]:
X_train,X_test,y_train,y_test= train_test_split(X,y,train_size=0.8,random_state=123)

In [171]:
print(X_train.head())

    WinterRain     AGST  HarvestRain
8          697  16.3000           52
7          830  17.3333           38
11         602  15.3667          267
4          582  16.4167          187
3          420  16.1333          110


In [172]:
print("shape of train data sets")
print(X_train.shape)
print(y_train.shape)

print("shape of train data sets")
print(X_test.shape)
print(y_test.shape)


shape of train data sets
(20, 3)
(20, 1)
shape of train data sets
(5, 3)
(5, 1)


In [173]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
lm.fit(X_train,y_train) # fit model

LinearRegression()

In [174]:
print(lm.coef_)

[[ 0.00142976  0.6924606  -0.00377696]]


In [175]:
print(lm.intercept_)

[-4.69864537]


In [176]:
predict_train = lm.predict(X_train)

In [177]:
predict_train

array([[7.38860024],
       [8.34715465],
       [5.79445428],
       [6.79509935],
       [6.65806132],
       [7.15207485],
       [7.59616493],
       [7.39554649],
       [6.46841319],
       [6.28849582],
       [6.71418203],
       [7.40753521],
       [7.57288035],
       [7.47003797],
       [7.19239437],
       [7.27640991],
       [6.66485852],
       [6.93740991],
       [7.40378682],
       [7.11743981]])

In [178]:
# error in Prediction
error_train = X_train - predict_train

In [179]:
error_train

WinterRain      AGST  HarvestRain
8   689.611400  8.911400    44.611400
7   821.652845  8.986145    29.652845
11  596.205546  9.572246   261.205546
4   575.204901  9.621601   180.204901
3   413.341939  9.475239   103.341939
24  755.847925  8.664625    43.847925
12  811.403835  8.937135    78.403835
16  614.604454  9.271154    81.604454
9   601.531587  9.248287   148.531587
14  603.711504  9.911504   285.711504
20  567.285818  9.585818   177.285818
0   592.592465  9.709165   152.592465
1   682.427120  9.160420    72.427120
10  394.529962  9.796662    88.529962
19  368.807606  9.874306   115.807606
17  543.723590  9.490290   104.723590
6   756.335141  9.751841   283.335141
23  814.062590  8.645890    80.062590
2   494.596213  9.746213   122.596213
13  706.882560  9.115860   110.882560

In [180]:
predict_test = lm.predict(X_test)

In [181]:
predict_test

array([[7.39499156],
       [7.21052235],
       [7.18801372],
       [5.84628932],
       [6.66210952]])

In [182]:
error_test = y_test - predict_test

In [183]:
error_test

Price
5   0.680708
21  0.081478
22 -0.066914
18  0.358611
15 -0.316210

In [184]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, mean_absolute_percentage_error
from math import sqrt

In [185]:
print("Evaluation metrics for train data")
print('\n')
# Actual value, prediction 
mse_train = mean_squared_error(y_train, predict_train)
print("Mean square error for train data (MSE) :", mse_train)

rmse_train = sqrt(mse_train)
print("Root Mean square error for train data (RMSE) :", rmse_train)

mae_train = mean_absolute_error(y_train, predict_train)
print("Root Mean absolute error for train data (MAE) :", mae_train)

mape_train = mean_absolute_percentage_error(y_train, predict_train)
print("Root Mean absolute percentage error for train data (MAPE) :", mape_train)

r_square = r2_score(y_train, predict_train)
print("R2 value for train data :", r_square)

Evaluation metrics for train data


Mean square error for train data (MSE) : 0.09206131850370818
Root Mean square error for train data (RMSE) : 0.30341608148499344
Root Mean absolute error for train data (MAE) : 0.2385327927780813
Root Mean absolute percentage error for train data (MAPE) : 0.03472631686583838
R2 value for train data : 0.7643043140887541


In [186]:
print("Evaluation metrics for test data")
print('\n')
# Actual value, prediction 
mse_test = mean_squared_error(y_test, predict_test)
print("Mean square error for test data (MSE) :", mse_test)

rmse_test = sqrt(mse_test)
print("Root Mean square error for test data (RMSE) :", rmse_test)

mae_test = mean_absolute_error(y_test, predict_test)
print("Root Mean absolute error for test data (MAE) :", mae_test)

mape_test = mean_absolute_percentage_error(y_test, predict_test)
print("Root Mean absolute percentage error for test data (MAPE) :", mape_test)


r_square_test = r2_score(y_test, predict_test)
print("R2 value for test data :", r_square_test)

Evaluation metrics for test data


Mean square error for test data (MSE) : 0.14061402365690406
Root Mean square error for test data (RMSE) : 0.3749853645902785
Root Mean absolute error for test data (MAE) : 0.3007840026314552
Root Mean absolute percentage error for test data (MAPE) : 0.04249695308584827
R2 value for test data : 0.6965309340203842
